name: 'Yandex message queue / AWS SQS'
description: 'Send message to Yandex message queue or AWS SQS'
branding:
  icon: 'message-square'
  color: 'orange'
inputs:
  sqs-url:
    description: 'SQS url to send message'
    required: true
  message:
    description: 'message boty to send'
    required: true
  endpoint:
    description: 'sqs endpoint'
    required: false
  region:
    description: 'sqs region'
    required: false
  message-group-id:
    description: 'sqs MessageGroupId'
    required: false
runs:
  using: 'node12'
  main: 'index.js'
